name: ci

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  THESIS_ROOT_FILE: main.tex
  THESIS_OUTPUT_DIR: build
  THESIS_PDF_NAME: corradini_carlo_computer_science_2022_2023.pdf

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            chktex -wall -n22 -n30 -e16 -q -f%f:%l:%c:%d:%k:%n:%m\n ${{ env.THESIS_ROOT_FILE }} \
              | tee /dev/stderr \
              | [ -z "$(</dev/stdin)" ]
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.THESIS_ROOT_FILE }}
          args: >-
            -interaction=nonstopmode
            -file-line-error
            -pdf
            -halt-on-error
            -outdir=${{ env.THESIS_OUTPUT_DIR }}
      - name: Rename
        run: |
          _file_name=$(basename -- ${{ env.THESIS_ROOT_FILE }})
          mv "${{ env.THESIS_OUTPUT_DIR }}/${_file_name%.*}.pdf" ${{ env.THESIS_OUTPUT_DIR }}/${{ env.THESIS_PDF_NAME }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            ${{ env.THESIS_OUTPUT_DIR }}/${{ env.THESIS_PDF_NAME }}
