name: ci

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore_paths: ./node_modules
      - name: Initialization
        run: |
          find ./scripts -type f -name "*.sh" -exec chmod +x {} \;
          ./scripts/init.sh
      - name: Check
        run: npm run check

  release:
    needs: ci
    if: needs.ci.result == 'success' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Initialization
        run: |
          find ./scripts -type f -name "*.sh" -exec chmod +x {} \;
          ./scripts/init.sh
      # TODO
      - name: Release
        uses: softprops/action-gh-release@v1
