name: ci

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            scheme-full
      - name: Install dependencies
        run: |
          npm ci
      - name: Check
        run: |
          npm run check
      - name: Compile
        run: |
          npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref , 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            LICENSE
            corradini_carlo_computer_science_2022_2023.pdf
